# Generated by Django 2.0 on 2020-06-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_author',
            name='f_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='作者id'),
        ),
        migrations.AlterField(
            model_name='t_author',
            name='f_name',
            field=models.CharField(max_length=16, unique=True, verbose_name='作者姓名'),
        ),
        migrations.AlterField(
            model_name='t_book',
            name='f_book_country',
            field=models.CharField(max_length=64, null=True, verbose_name='书籍国家'),
        ),
        migrations.AlterField(
            model_name='t_book',
            name='f_book_description',
            field=models.CharField(max_length=64, null=True, verbose_name='书籍描述'),
        ),
        migrations.AlterField(
            model_name='t_book',
            name='f_book_name',
            field=models.CharField(max_length=64, null=True, verbose_name='书籍名称'),
        ),
        migrations.AlterField(
            model_name='t_book',
            name='f_book_price',
            field=models.IntegerField(default=99, null=True, verbose_name='书籍价格'),
        ),
        migrations.AlterField(
            model_name='t_book',
            name='f_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='书籍id'),
        ),
        migrations.AlterField(
            model_name='t_publisher',
            name='f_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='出版社id'),
        ),
        migrations.AlterField(
            model_name='t_publisher',
            name='f_publisher_name',
            field=models.CharField(max_length=64, null=True, verbose_name='出版社名称'),
        ),
    ]
