# Generated by Django 2.0 on 2020-06-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200609_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_author',
            options={'verbose_name': '作者表'},
        ),
    ]
