# Generated by Django 2.0 on 2020-06-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20200609_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_author',
            options={'verbose_name_plural': '作者'},
        ),
    ]
