# Generated by Django 2.0 on 2020-06-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20200609_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_book',
            options={'verbose_name_plural': '书籍'},
        ),
        migrations.AlterModelOptions(
            name='t_publisher',
            options={'verbose_name_plural': '出版社'},
        ),
    ]
